apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bottom-dove-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bottom-dove-go 
  name: bottom-dove-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bottom-dove-go 
